/*
 *  BSD LICENSE
 *
 *  Copyright (c) 2011-2018 Broadcom.  All Rights Reserved.
 *  The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *    * Redistributions in binary form must reproduce the above copyright
 *      notice, this list of conditions and the following disclaimer in
 *      the documentation and/or other materials provided with the
 *      distribution.
 *    * Neither the name of Intel Corporation nor the names of its
 *      contributors may be used to endorse or promote products derived
 *      from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

/**
 * @file
 * Define all the ASC/ASCQ check condition response valis
 */


#if !defined(__SCSI_ASC_ASCQ_H__)
#define __SCSI_ASC_ASCQ_H__

//
//  SCSI_ASC/ASCQ defines ... Taken from SPC4.15
//
//  16 bit value, high 8 is SCSI_ASC, low 8 is ASCQ
//

#define SCSI_ASC(x)	(((x) >> 8) & 0xff)
#define SCSI_ASCQ(x)	((x) & 0xff)

#define SCSI_ASC_NO_ADDITIONAL_SENSE_INFORMATION					0x0000
#define SCSI_ASC_FILEMARK_DETECTED							0x0001
#define SCSI_ASC_ENDOF_PARTITION_MEDIUM_DETECTED					0x0002
#define SCSI_ASC_SETMARK_DETECTED							0x0003
#define SCSI_ASC_BEGINNINGOF_PARTITION_MEDIUM_DETECTED					0x0004
#define SCSI_ASC_ENDOF_DATA_DETECTED							0x0005
#define SCSI_ASC_IO_PROCESS_TERMINATED							0x0006
#define SCSI_ASC_PROGRAMMABLE_EARLY_WARNING_DETECTED					0x0007
#define SCSI_ASC_AUDIO_PLAY_OPERATION_IN_PROGRESS					0x0011
#define SCSI_ASC_AUDIO_PLAY_OPERATION_PAUSED						0x0012
#define SCSI_ASC_AUDIO_PLAY_OPERATION_SUCCESSFULLY_COMPLETED				0x0013
#define SCSI_ASC_AUDIO_PLAY_OPERATION_STOPPED_DUE_TO_ERROR				0x0014
#define SCSI_ASC_NO_CURRENT_AUDIO_STATUS_TO_RETURN					0x0015
#define SCSI_ASC_OPERATION_IN_PROGRESS							0x0016
#define SCSI_ASC_CLEANING_REQUESTED							0x0017
#define SCSI_ASC_ERASE_OPERATION_IN_PROGRESS						0x0018
#define SCSI_ASC_LOCATE_OPERATION_IN_PROGRESS                                           0x0019
#define SCSI_ASC_REWIND_OPERATION_IN_PROGRESS                                           0x001A
#define SCSI_ASC_SET_CAPACITY_OPERATION_IN_PROGRESS                                     0x001B
#define SCSI_ASC_VERIFY_OPERATION_IN_PROGRESS                                           0x001C
#define SCSI_ASC_ATA_PASS_THROUGH_INFORMATION_AVAILABLE                                 0x001D
#define SCSI_ASC_CONFLICTING_SA_CREATION_REQUEST                                        0x001E
#define SCSI_ASC_NO_INDEX_SECTOR_SIGNAL                                                 0x0100
#define SCSI_ASC_NO_SEEK_COMPLETE                                                       0x0200
#define SCSI_ASC_PERIPHERAL_DEVICE_WRITE_FAULT                                          0x0300
#define SCSI_ASC_NO_WRITE_CURRENT                                                       0x0301
#define SCSI_ASC_EXCESSIVE_WRITE_ERRORS                                                 0x0302
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_CAUSE_NOT_REPORTABLE                            0x0400
#define SCSI_ASC_LOGICAL_UNIT_IS_IN_PROCESS_OF_BECOMING_READY                           0x0401
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_INITIALIZING_COMMAND_REQUIRED                   0x0402
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_MANUAL_INTERVENTION_REQUIRED                    0x0403
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_FORMAT_IN_PROGRESS                              0x0404
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_REBUILD_IN_PROGRESS                             0x0405
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_RECALCULATION_IN_PROGRESS                       0x0406
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_OPERATION_IN_PROGRESS                           0x0407
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_LONG_WRITE_IN_PROGRESS                          0x0408
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_SELFTEST_IN_PROGRESS                            0x0409
#define SCSI_ASC_LOGICAL_UNIT_NOT_ACCESSIBLE_ASYMMETRIC_ACCESS_STATE_TRANSITION         0x040A
#define SCSI_ASC_LOGICAL_UNIT_NOT_ACCESSIBLE_TARGET_PORT_IN_STANDBY_STATE               0x040B
#define SCSI_ASC_LOGICAL_UNIT_NOT_ACCESSIBLE_TARGET_PORT_IN_UNAVAILABLE_STATE           0x040C
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_STRUCTURE_CHECK_REQUIRED                        0x040D
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_AUXILIARY_MEMORY_NOT_ACCESSIBLE                 0x0410
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_NOTIFY_ENABLE_SPINUP_REQUIRED                   0x0411
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_OFFLINE                                         0x0412
#define SCSI_ASC_LOGICAL_UNIT_NOT_READY_SA_CREATION_IN_PROGRESS                         0x0413
#define SCSI_ASC_LOGICAL_UNIT_DOES_NOT_RESPOND_TO_SELECTION                             0x0500
#define SCSI_ASC_NO_REFERENCE_POSITION_FOUND                                            0x0600
#define SCSI_ASC_MULTIPLE_PERIPHERAL_DEVICES_SELECTED                                   0x0700
#define SCSI_ASC_LOGICAL_UNIT_COMMUNICATION_FAILURE                                     0x0800
#define SCSI_ASC_LOGICAL_UNIT_COMMUNICATION_TIMEOUT                                     0x0801
#define SCSI_ASC_LOGICAL_UNIT_COMMUNICATION_PARITY_ERROR                                0x0802
#define SCSI_ASC_LOGICAL_UNIT_COMMUNICATION_CRC_ERROR                                   0x0803
#define SCSI_ASC_UNREACHABLE_COPY_TARGET                                                0x0804
#define SCSI_ASC_TRACK_FOLLOWING_ERROR                                                  0x0900
#define SCSI_ASC_TRACKING_SERVO_FAILURE                                                 0x0901
#define SCSI_ASC_FOCUS_SERVO_FAILURE                                                    0x0902
#define SCSI_ASC_SPINDLE_SERVO_FAILURE                                                  0x0903
#define SCSI_ASC_HEAD_SELECT_FAULT                                                      0x0904
#define SCSI_ASC_ERROR_LOG_OVERFLOW                                                     0x0A00
#define SCSI_ASC_WARNING                                                                0x0B00
#define SCSI_ASC_WARNING_SPECIFIED_TEMPERATURE_EXCEEDED                                 0x0B01
#define SCSI_ASC_WARNING_ENCLOSURE_DEGRADED                                             0x0B02
#define SCSI_ASC_WARNING_BACKGROUND_SELF_TEST_FAILED                                    0x0B03
#define SCSI_ASC_AEBKVF_WARNING_BACKGROUND_PRE_SCAN_DETECTED_MEDIUM_ERROR               0x0B04
#define SCSI_ASC_AEBKVF_WARNING_BACKGROUND_MEDIUM_SCAN_DETECTED_MEDIUM_ERROR            0x0B05
#define SCSI_ASC_WARNING_NON_VOLATILE_CACHE_NOW_VOLATILE                                0x0B06
#define SCSI_ASC_WARNING_DEGRADED_POWER_TO_NON_VOLATILE_CACHE                           0x0B07
#define SCSI_ASC_WRITE_ERROR                                                            0x0C00
#define SCSI_ASC_WRITE_ERROR_RECOVERED_WITH_AUTO_REALLOCATION                           0x0C01
#define SCSI_ASC_WRITE_ERROR_AUTO_REALLOCATION_FAILED                                   0x0C02
#define SCSI_ASC_WRITE_ERROR_RECOMMEND_REASSIGNMENT                                     0x0C03
#define SCSI_ASC_COMPRESSION_CHECK_MISCOMPARE_ERROR                                     0x0C04
#define SCSI_ASC_DATA_EXPANSION_OCCURRED_DURING_COMPRESSION                             0x0C05
#define SCSI_ASC_BLOCK_NOT_COMPRESSIBLE                                                 0x0C06
#define SCSI_ASC_WRITE_ERROR_RECOVERY_NEEDED                                            0x0C07
#define SCSI_ASC_WRITE_ERROR_RECOVERY_FAILED                                            0x0C08
#define SCSI_ASC_WRITE_ERROR_LOSS_OF_STREAMING                                          0x0C09
#define SCSI_ASC_WRITE_ERROR_PADDING_BLOCKS_ADDED                                       0x0C0A
#define SCSI_ASC_AUXILIARY_MEMORY_WRITE_ERROR                                           0x0C0B
#define SCSI_ASC_AEBKVF_WRITE_ERROR_UNEXPECTED_UNSOLICITED_DATA                         0x0C0C
#define SCSI_ASC_AEBKVF_WRITE_ERROR_NOT_ENOUGH_UNSOLICITED_DATA                         0x0C0D
#define SCSI_ASC_DEFECTS_IN_ERROR_WINDOW                                                0x0C0F
#define SCSI_ASC_ERROR_DETECTED_BY_THIRD_PARTY_TEMPORARY_INITIATOR                      0x0D00
#define SCSI_ASC_THIRD_PARTY_DEVICE_FAILURE                                             0x0D01
#define SCSI_ASC_COPY_TARGET_DEVICE_NOT_REACHABLE                                       0x0D02
#define SCSI_ASC_INCORRECT_COPY_TARGET_DEVICE_TYPE                                      0x0D03
#define SCSI_ASC_COPY_TARGET_DEVICE_DATA_UNDERRUN                                       0x0D04
#define SCSI_ASC_COPY_TARGET_DEVICE_DATA_OVERRUN                                        0x0D05
#define SCSI_ASC_INVALID_INFORMATION_UNIT                                               0x0E00
#define SCSI_ASC_INFORMATION_UNIT_TOO_SHORT                                             0x0E01
#define SCSI_ASC_INFORMATION_UNIT_TOO_LONG                                              0x0E02
#define SCSI_ASC_INVALID_FIELD_IN_COMMAND_INFORMATION_UNIT                              0x0E03
#define SCSI_ASC_ID_CRC_OR_ECC_ERROR                                                    0x1000
#define SCSI_ASC_LOGICAL_BLOCK_GUARD_CHECK_FAILED                                       0x1001
#define SCSI_ASC_LOGICAL_BLOCK_APPLICATION_TAG_CHECK_FAILED                             0x1002
#define SCSI_ASC_LOGICAL_BLOCK_REFERENCE_TAG_CHECK_FAILED                               0x1003
#define SCSI_ASC_UNRECOVERED_READ_ERROR                                                 0x1100
#define SCSI_ASC_READ_RETRIES_EXHAUSTED                                                 0x1101
#define SCSI_ASC_ERROR_TOO_LONG_TO_CORRECT                                              0x1102
#define SCSI_ASC_MULTIPLE_READ_ERRORS                                                   0x1103
#define SCSI_ASC_UNRECOVERED_READ_ERROR_AUTO_REALLOCATE_FAILED                          0x1104
#define SCSI_ASC_L_EC_UNCORRECTABLE_ERROR                                               0x1105
#define SCSI_ASC_CIRC_UNRECOVERED_ERROR                                                 0x1106
#define SCSI_ASC_DATA_RESYNCHRONIZATION_ERROR                                           0x1107
#define SCSI_ASC_INCOMPLETE_BLOCK_READ                                                  0x1108
#define SCSI_ASC_NO_GAP_FOUND                                                           0x1109
#define SCSI_ASC_MISCORRECTED_ERROR                                                     0x110A
#define SCSI_ASC_UNRECOVERED_READ_ERROR_RECOMMEND_REASSIGNMENT                          0x110B
#define SCSI_ASC_UNRECOVERED_READ_ERROR_RECOMMEND_REWRITE_THE_DATA                      0x110C
#define SCSI_ASC_DECOMPRESSION_CRC_ERROR                                                0x110D
#define SCSI_ASC_CANNOT_DECOMPRESS_USING_DECLARED_ALGORITHM                             0x110E
#define SCSI_ASC_ERROR_READING_UPC_EAN_NUMBER                                           0x110F
#define SCSI_ASC_ERROR_READING_ISRC_NUMBER                                              0x1110
#define SCSI_ASC_READ_ERROR_LOSS_OF_STREAMING                                           0x1111
#define SCSI_ASC_AUXILIARY_MEMORY_READ_ERROR                                            0x1112
#define SCSI_ASC_READ_ERROR_FAILED_RETRANSMISSION_REQUEST                               0x1113
#define SCSI_ASC_READ_ERROR_LBA_MARKED_BAD_BY_APPLICATION_CLIENT                        0x1114
#define SCSI_ASC_ADDRESS_MARK_NOT_FOUND_FOR_ID_FIELD                                    0x1200
#define SCSI_ASC_ADDRESS_MARK_NOT_FOUND_FOR_DATA_FIELD                                  0x1300
#define SCSI_ASC_RECORDED_ENTITY_NOT_FOUND                                              0x1400
#define SCSI_ASC_RECORD_NOT_FOUND                                                       0x1401
#define SCSI_ASC_FILEMARK_OR_SETMARK_NOT_FOUND                                          0x1402
#define SCSI_ASC_ENDOF_DATA_NOT_FOUND                                                   0x1403
#define SCSI_ASC_BLOCK_SEQUENCE_ERROR                                                   0x1404
#define SCSI_ASC_RECORD_NOT_FOUND_RECOMMEND_REASSIGNMENT                                0x1405
#define SCSI_ASC_RECORD_NOT_FOUND_DATA_AUTO_REALLOCATED                                 0x1406
#define SCSI_ASC_LOCATE_OPERATION_FAILURE                                               0x1407
#define SCSI_ASC_RANDOM_POSITIONING_ERROR                                               0x1500
#define SCSI_ASC_MECHANICAL_POSITIONING_ERROR                                           0x1501
#define SCSI_ASC_POSITIONING_ERROR_DETECTED_BY_READ_OF_MEDIUM                           0x1502
#define SCSI_ASC_DATA_SYNCHRONIZATION_MARK_ERROR                                        0x1600
#define SCSI_ASC_DATA_SYNC_ERROR_DATA_REWRITTEN                                         0x1601
#define SCSI_ASC_DATA_SYNC_ERROR_RECOMMEND_REWRITE                                      0x1602
#define SCSI_ASC_DATA_SYNC_ERROR_DATA_AUTO_REALLOCATED                                  0x1603
#define SCSI_ASC_DATA_SYNC_ERROR_RECOMMEND_REASSIGNMENT                                 0x1604
#define SCSI_ASC_RECOVERED_DATA_WITH_NO_ERROR_CORRECTION_APPLIED                        0x1700
#define SCSI_ASC_RECOVERED_DATA_WITH_RETRIES                                            0x1701
#define SCSI_ASC_RECOVERED_DATA_WITH_POSITIVE_HEAD_OFFSET                               0x1702
#define SCSI_ASC_RECOVERED_DATA_WITH_NEGATIVE_HEAD_OFFSET                               0x1703
#define SCSI_ASC_RECOVERED_DATA_WITH_RETRIES_AND_OR_CIRC_APPLIED                        0x1704
#define SCSI_ASC_RECOVERED_DATA_USING_PREVIOUS_SECTOR_ID                                0x1705
#define SCSI_ASC_RECOVERED_DATA_WITHOUT_ECC_DATA_AUTO_REALLOCATED                       0x1706
#define SCSI_ASC_RECOVERED_DATA_WITHOUT_ECC_RECOMMEND_REASSIGNMENT                      0x1707
#define SCSI_ASC_RECOVERED_DATA_WITHOUT_ECC_RECOMMEND_REWRITE                           0x1708
#define SCSI_ASC_RECOVERED_DATA_WITHOUT_ECC_DATA_REWRITTEN                              0x1709
#define SCSI_ASC_RECOVERED_DATA_WITH_ERROR_CORRECTION_APPLIED                           0x1800
#define SCSI_ASC_RECOVERED_DATA_WITH_ERROR_CORRECTION_RETRIES_APPLIED                   0x1801
#define SCSI_ASC_RECOVERED_DATA_DATA_AUTO_REALLOCATED                                   0x1802
#define SCSI_ASC_RECOVERED_DATA_WITH_CIRC                                               0x1803
#define SCSI_ASC_RECOVERED_DATA_WITH_LEC                                                0x1804
#define SCSI_ASC_RECOVERED_DATA_RECOMMEND_REASSIGNMENT                                  0x1805
#define SCSI_ASC_RECOVERED_DATA_RECOMMEND_REWRITE                                       0x1806
#define SCSI_ASC_RECOVERED_DATA_WITH_ECC_DATA_REWRITTEN                                 0x1807
#define SCSI_ASC_RECOVERED_DATA_WITH_LINKING                                            0x1808
#define SCSI_ASC_DEFECT_LIST_ERROR                                                      0x1900
#define SCSI_ASC_DEFECT_LIST_NOT_AVAILABLE                                              0x1901
#define SCSI_ASC_DEFECT_LIST_ERROR_IN_PRIMARY_LIST                                      0x1902
#define SCSI_ASC_DEFECT_LIST_ERROR_IN_GROWN_LIST                                        0x1903
#define SCSI_ASC_PARAMETER_LIST_LENGTH_ERROR                                            0x1A00
#define SCSI_ASC_SYNCHRONOUS_DATA_TRANSFER_ERROR                                        0x1B00
#define SCSI_ASC_DEFECT_LIST_NOT_FOUND                                                  0x1C00
#define SCSI_ASC_PRIMARY_DEFECT_LIST_NOT_FOUND                                          0x1C01
#define SCSI_ASC_GROWN_DEFECT_LIST_NOT_FOUND                                            0x1C02
#define SCSI_ASC_MISCOMPARE_DURING_VERIFY_OPERATION                                     0x1D00
#define SCSI_ASC_RECOVERED_ID_WITH_ECC_CORRECTION                                       0x1E00
#define SCSI_ASC_PARTIAL_DEFECT_LIST_TRANSFER                                           0x1F00
#define SCSI_ASC_INVALID_COMMAND_OPERATION_CODE                                         0x2000
#define SCSI_ASC_ACCESS_DENIED_INITIATOR_PENDING_ENROLLED                               0x2001
#define SCSI_ASC_ACCESS_DENIED_NO_ACCESS_RIGHTS                                         0x2002
#define SCSI_ASC_ACCESS_DENIED_INVALID_MGMT_ID_KEY                                      0x2003
#define SCSI_ASC_ILLEGAL_COMMAND_WHILE_IN_WRITE_CAPABLE_STATE                           0x2004
#define SCSI_ASC_ILLEGAL_COMMAND_WHILE_IN_EXPLICIT_ADDRESS_MODE                         0x2006
#define SCSI_ASC_ILLEGAL_COMMAND_WHILE_IN_IMPLICIT_ADDRESS_MODE                         0x2007
#define SCSI_ASC_ACCESS_DENIED_ENROLLMENT_CONFLICT                                      0x2008
#define SCSI_ASC_ACCESS_DENIED_INVALID_LU_IDENTIFIER                                    0x2009
#define SCSI_ASC_ACCESS_DENIED_INVALID_PROXY_TOKEN                                      0x200A
#define SCSI_ASC_ACCESS_DENIED_ACL_LUN_CONFLICT                                         0x200B
#define SCSI_ASC_LOGICAL_BLOCK_ADDRESS_OUT_OF_RANGE                                     0x2100
#define SCSI_ASC_INVALID_ELEMENT_ADDRESS                                                0x2101
#define SCSI_ASC_INVALID_ADDRESS_FOR_WRITE                                              0x2102
#define SCSI_ASC_INVALID_WRITE_CROSSING_LAYER_JUMP                                      0x2103
#define SCSI_ASC_ILLEGAL_FUNCTION                                                       0x2200
#define SCSI_ASC_INVALID_FIELD_IN_CDB                                                   0x2400
#define SCSI_ASC_CDB_DECRYPTION_ERROR                                                   0x2401
#define SCSI_ASC_SECURITY_AUDIT_VALUE_FROZEN                                            0x2404
#define SCSI_ASC_SECURITY_WORKING_KEY_FROZEN                                            0x2405
#define SCSI_ASC_NONCE_NOT_UNIQUE                                                       0x2406
#define SCSI_ASC_NONCE_TIMESTAMP_OUT_OF_RANGE                                           0x2407
#define SCSI_ASC_INVALID_XCDB                                                           0x2408
#define SCSI_ASC_LOGICAL_UNIT_NOT_SUPPORTED                                             0x2500
#define SCSI_ASC_INVALID_FIELD_IN_PARAMETER_LIST                                        0x2600
#define SCSI_ASC_PARAMETER_NOT_SUPPORTED                                                0x2601
#define SCSI_ASC_PARAMETER_VALUE_INVALID                                                0x2602
#define SCSI_ASC_THRESHOLD_PARAMETERS_NOT_SUPPORTED                                     0x2603
#define SCSI_ASC_INVALID_RELEASE_OF_PERSISTENT_RESERVATION                              0x2604
#define SCSI_ASC_DATA_DECRYPTION_ERROR                                                  0x2605
#define SCSI_ASC_TOO_MANY_TARGET_DESCRIPTORS                                            0x2606
#define SCSI_ASC_UNSUPPORTED_TARGET_DESCRIPTOR_TYPE_CODE                                0x2607
#define SCSI_ASC_TOO_MANY_SEGMENT_DESCRIPTORS                                           0x2608
#define SCSI_ASC_UNSUPPORTED_SEGMENT_DESCRIPTOR_TYPE_CODE                               0x2609
#define SCSI_ASC_UNEXPECTED_INEXACT_SEGMENT                                             0x260A
#define SCSI_ASC_INLINE_DATA_LENGTH_EXCEEDED                                            0x260B
#define SCSI_ASC_INVALID_OPERATION_FOR_COPY_SOURCE_OR_DESTINATION                       0x260C
#define SCSI_ASC_COPY_SEGMENT_GRANULARITY_VIOLATION                                     0x260D
#define SCSI_ASC_INVALID_PARAMETER_WHILE_PORT_IS_ENABLED                                0x260E
#define SCSI_ASC_INVALID_DATAOUT_BUFFER_INTEGRITY_CHECK_VALUE                           0x260F
#define SCSI_ASC_DATA_DECRYPTION_KEY_FAIL_LIMIT_REACHED                                 0x2610
#define SCSI_ASC_INCOMPLETE_KEYASSOCIATED_DATA_SET                                      0x2611
#define SCSI_ASC_VENDOR_SPECIFIC_KEY_REFERENCE_NOT_FOUND                                0x2612
#define SCSI_ASC_WRITE_PROTECTED                                                        0x2700
#define SCSI_ASC_HARDWARE_WRITE_PROTECTED                                               0x2701
#define SCSI_ASC_LOGICAL_UNIT_SOFTWARE_WRITE_PROTECTED                                  0x2702
#define SCSI_ASC_ASSOCIATED_WRITE_PROTECT                                               0x2703
#define SCSI_ASC_PERSISTENT_WRITE_PROTECT                                               0x2704
#define SCSI_ASC_PERMANENT_WRITE_PROTECT                                                0x2705
#define SCSI_ASC_CONDITIONAL_WRITE_PROTECT                                              0x2706
#define SCSI_ASC_NOT_READY_TO_READY_CHANGE_MEDIUM_MAY_HAVE_CHANGED                      0x2800
#define SCSI_ASC_IMPORT_OR_EXPORT_ELEMENT_ACCESSED                                      0x2801
#define SCSI_ASC_FORMATLAYER_MAY_HAVE_CHANGED                                           0x2802
#define SCSI_ASC_IMPORT_EXPORT_ELEMENT_ACCESSED_MEDIUM_CHANGED                          0x2803
#define SCSI_ASC_POWER_ON_RESET_OR_BUS_DEVICE_RESET_OCCURRED                            0x2900
#define SCSI_ASC_POWER_ON_OCCURRED                                                      0x2901
#define SCSI_ASC_SCSI_BUS_RESET_OCCURRED                                                0x2902
#define SCSI_ASC_BUS_DEVICE_RESET_FUNCTION_OCCURRED                                     0x2903
#define SCSI_ASC_DEVICE_INTERNAL_RESET                                                  0x2904
#define SCSI_ASC_TRANSCEIVER_MODE_CHANGED_TO_SINGLEENDED                                0x2905
#define SCSI_ASC_TRANSCEIVER_MODE_CHANGED_TO_LVD                                        0x2906
#define SCSI_ASC_I_T_NEXUS_LOSS_OCCURRED                                                0x2907
#define SCSI_ASC_PARAMETERS_CHANGED                                                     0x2A00
#define SCSI_ASC_MODE_PARAMETERS_CHANGED                                                0x2A01
#define SCSI_ASC_LOG_PARAMETERS_CHANGED                                                 0x2A02
#define SCSI_ASC_RESERVATIONS_PREEMPTED                                                 0x2A03
#define SCSI_ASC_RESERVATIONS_RELEASED                                                  0x2A04
#define SCSI_ASC_REGISTRATIONS_PREEMPTED                                                0x2A05
#define SCSI_ASC_ASYMMETRIC_ACCESS_STATE_CHANGED                                        0x2A06
#define SCSI_ASC_IMPLICIT_ASYMMETRIC_ACCESS_STATE_TRANSITION_FAILED                     0x2A07
#define SCSI_ASC_PRIORITY_CHANGED                                                       0x2A08
#define SCSI_ASC_CAPACITY_DATA_HAS_CHANGED                                              0x2A09
#define SCSI_ASC_ERROR_HISTORY_I_T_NEXUS_CLEARED                                        0x2A0A
#define SCSI_ASC_ERROR_HISTORY_SNAPSHOT_RELEASED                                        0x2A0B
#define SCSI_ASC_ERROR_RECOVERY_ATTRIBUTES_HAVE_CHANGED                                 0x2A0C
#define SCSI_ASC_DATA_ENCRYPTION_CAPABILITIES_CHANGED                                   0x2A0D
#define SCSI_ASC_TIMESTAMP_CHANGED                                                      0x2A10
#define SCSI_ASC_DATA_ENCRYPTION_PARAMETERS_CHANGED_BY_ANOTHER_I_T_NEXUS                0x2A11
#define SCSI_ASC_DATA_ENCRYPTION_PARAMETERS_CHANGED_BY_VENDOR_SPECIFIC_EVENT            0x2A12
#define SCSI_ASC_DATA_ENCRYPTION_KEY_INSTANCE_COUNTER_HAS_CHANGED                       0x2A13
#define SCSI_ASC_CREATION_CAPABILITIES_DATA_HAS_CHANGED                                 0x2A14
#define SCSI_ASC_COPY_CANNOT_EXECUTE_SINCE_HOST_CANNOT_DISCONNECT                       0x2B00
#define SCSI_ASC_COMMAND_SEQUENCE_ERROR                                                 0x2C00
#define SCSI_ASC_TOO_MANY_WINDOWS_SPECIFIED                                             0x2C01
#define SCSI_ASC_INVALID_COMBINATION_OF_WINDOWS_SPECIFIED                               0x2C02
#define SCSI_ASC_CURRENT_PROGRAM_AREA_IS_NOT_EMPTY                                      0x2C03
#define SCSI_ASC_CURRENT_PROGRAM_AREA_IS_EMPTY                                          0x2C04
#define SCSI_ASC_ILLEGAL_POWER_CONDITION_REQUEST                                        0x2C05
#define SCSI_ASC_PERSISTENT_PREVENT_CONFLICT                                            0x2C06
#define SCSI_ASC_PREVIOUS_BUSY_STATUS                                                   0x2C07
#define SCSI_ASC_PREVIOUS_TASK_SET_FULL_STATUS                                          0x2C08
#define SCSI_ASC_EBKVF_PREVIOUS_RESERVATION_CONFLICT_STATUS                             0x2C09
#define SCSI_ASC_PARTITION_OR_COLLECTION_CONTAINS_USER_OBJECTS                          0x2C0A
#define SCSI_ASC_NOT_RESERVED                                                           0x2C0B
#define SCSI_ASC_OVERWRITE_ERROR_ON_UPDATE_IN_PLACE                                     0x2D00
#define SCSI_ASC_INSUFFICIENT_TIME_FOR_OPERATION                                        0x2E00
#define SCSI_ASC_COMMANDS_CLEARED_BY_ANOTHER_INITIATOR                                  0x2F00
#define SCSI_ASC_COMMANDS_CLEARED_BY_POWER_LOSS_NOTIFICATION                            0x2F01
#define SCSI_ASC_COMMANDS_CLEARED_BY_DEVICE_SERVER                                      0x2F02
#define SCSI_ASC_INCOMPATIBLE_MEDIUM_INSTALLED                                          0x3000
#define SCSI_ASC_CANNOT_READ_MEDIUM_UNKNOWN_FORMAT                                      0x3001
#define SCSI_ASC_CANNOT_READ_MEDIUM_INCOMPATIBLE_FORMAT                                 0x3002
#define SCSI_ASC_CLEANING_CARTRIDGE_INSTALLED                                           0x3003
#define SCSI_ASC_CANNOT_WRITE_MEDIUM_UNKNOWN_FORMAT                                     0x3004
#define SCSI_ASC_CANNOT_WRITE_MEDIUM_INCOMPATIBLE_FORMAT                                0x3005
#define SCSI_ASC_CANNOT_FORMAT_MEDIUM_INCOMPATIBLE_MEDIUM                               0x3006
#define SCSI_ASC_CLEANING_FAILURE                                                       0x3007
#define SCSI_ASC_CANNOT_WRITE_APPLICATION_CODE_MISMATCH                                 0x3008
#define SCSI_ASC_CURRENT_SESSION_NOT_FIXATED_FOR_APPEND                                 0x3009
#define SCSI_ASC_CLEANING_REQUEST_REJECTED                                              0x300A
#define SCSI_ASC_WORM_MEDIUM_OVERWRITE_ATTEMPTED                                        0x300C
#define SCSI_ASC_WORM_MEDIUM_INTEGRITY_CHECK                                            0x300D
#define SCSI_ASC_MEDIUM_NOT_FORMATTED                                                   0x3010
#define SCSI_ASC_INCOMPATIBLE_VOLUME_TYPE                                               0x3011
#define SCSI_ASC_INCOMPATIBLE_VOLUME_QUALIFIER                                          0x3012
#define SCSI_ASC_MEDIUM_FORMAT_CORRUPTED                                                0x3100
#define SCSI_ASC_FORMAT_COMMAND_FAILED                                                  0x3101
#define SCSI_ASC_ZONED_FORMATTING_FAILED_DUE_TO_SPARE_LINKING                           0x3102
#define SCSI_ASC_NO_DEFECT_SPARE_LOCATION_AVAILABLE                                     0x3200
#define SCSI_ASC_DEFECT_LIST_UPDATE_FAILURE                                             0x3201
#define SCSI_ASC_TAPE_LENGTH_ERROR                                                      0x3300
#define SCSI_ASC_ENCLOSURE_FAILURE                                                      0x3400
#define SCSI_ASC_ENCLOSURE_SERVICES_FAILURE                                             0x3500
#define SCSI_ASC_UNSUPPORTED_ENCLOSURE_FUNCTION                                         0x3501
#define SCSI_ASC_ENCLOSURE_SERVICES_UNAVAILABLE                                         0x3502
#define SCSI_ASC_ENCLOSURE_SERVICES_TRANSFER_FAILURE                                    0x3503
#define SCSI_ASC_ENCLOSURE_SERVICES_TRANSFER_REFUSED                                    0x3504
#define SCSI_ASC_CURRENT_PROGRAM_AREA_IS_EMPTY                                          0x2C04
#define SCSI_ASC_ILLEGAL_POWER_CONDITION_REQUEST                                        0x2C05
#define SCSI_ASC_PERSISTENT_PREVENT_CONFLICT                                            0x2C06
#define SCSI_ASC_PREVIOUS_BUSY_STATUS                                                   0x2C07
#define SCSI_ASC_PREVIOUS_TASK_SET_FULL_STATUS                                          0x2C08
#define SCSI_ASC_EBKVF_PREVIOUS_RESERVATION_CONFLICT_STATUS                             0x2C09
#define SCSI_ASC_PARTITION_OR_COLLECTION_CONTAINS_USER_OBJECTS                          0x2C0A
#define SCSI_ASC_NOT_RESERVED                                                           0x2C0B
#define SCSI_ASC_OVERWRITE_ERROR_ON_UPDATE_IN_PLACE                                     0x2D00
#define SCSI_ASC_INSUFFICIENT_TIME_FOR_OPERATION                                        0x2E00
#define SCSI_ASC_COMMANDS_CLEARED_BY_ANOTHER_INITIATOR                                  0x2F00
#define SCSI_ASC_COMMANDS_CLEARED_BY_POWER_LOSS_NOTIFICATION                            0x2F01
#define SCSI_ASC_COMMANDS_CLEARED_BY_DEVICE_SERVER                                      0x2F02
#define SCSI_ASC_INCOMPATIBLE_MEDIUM_INSTALLED                                          0x3000
#define SCSI_ASC_CANNOT_READ_MEDIUM_UNKNOWN_FORMAT                                      0x3001
#define SCSI_ASC_CANNOT_READ_MEDIUM_INCOMPATIBLE_FORMAT                                 0x3002
#define SCSI_ASC_CLEANING_CARTRIDGE_INSTALLED                                           0x3003
#define SCSI_ASC_CANNOT_WRITE_MEDIUM_UNKNOWN_FORMAT                                     0x3004
#define SCSI_ASC_CANNOT_WRITE_MEDIUM_INCOMPATIBLE_FORMAT                                0x3005
#define SCSI_ASC_CANNOT_FORMAT_MEDIUM_INCOMPATIBLE_MEDIUM                               0x3006
#define SCSI_ASC_CLEANING_FAILURE                                                       0x3007
#define SCSI_ASC_CANNOT_WRITE_APPLICATION_CODE_MISMATCH                                 0x3008
#define SCSI_ASC_CURRENT_SESSION_NOT_FIXATED_FOR_APPEND                                 0x3009
#define SCSI_ASC_CLEANING_REQUEST_REJECTED                                              0x300A
#define SCSI_ASC_WORM_MEDIUM_OVERWRITE_ATTEMPTED                                        0x300C
#define SCSI_ASC_WORM_MEDIUM_INTEGRITY_CHECK                                            0x300D
#define SCSI_ASC_MEDIUM_NOT_FORMATTED                                                   0x3010
#define SCSI_ASC_INCOMPATIBLE_VOLUME_TYPE                                               0x3011
#define SCSI_ASC_INCOMPATIBLE_VOLUME_QUALIFIER                                          0x3012
#define SCSI_ASC_MEDIUM_FORMAT_CORRUPTED                                                0x3100
#define SCSI_ASC_FORMAT_COMMAND_FAILED                                                  0x3101
#define SCSI_ASC_ZONED_FORMATTING_FAILED_DUE_TO_SPARE_LINKING                           0x3102
#define SCSI_ASC_NO_DEFECT_SPARE_LOCATION_AVAILABLE                                     0x3200
#define SCSI_ASC_DEFECT_LIST_UPDATE_FAILURE                                             0x3201
#define SCSI_ASC_TAPE_LENGTH_ERROR                                                      0x3300
#define SCSI_ASC_ENCLOSURE_FAILURE                                                      0x3400
#define SCSI_ASC_ENCLOSURE_SERVICES_FAILURE                                             0x3500
#define SCSI_ASC_UNSUPPORTED_ENCLOSURE_FUNCTION                                         0x3501
#define SCSI_ASC_ENCLOSURE_SERVICES_UNAVAILABLE                                         0x3502
#define SCSI_ASC_ENCLOSURE_SERVICES_TRANSFER_FAILURE                                    0x3503
#define SCSI_ASC_ENCLOSURE_SERVICES_TRANSFER_REFUSED                                    0x3504
#define SCSI_ASC_ENCLOSURE_SERVICES_CHECKSUM_ERROR                                      0x3505
#define SCSI_ASC_RIBBON_INK_OR_TONER_FAILURE                                            0x3600
#define SCSI_ASC_ROUNDED_PARAMETER                                                      0x3700
#define SCSI_ASC_EVENT_STATUS_NOTIFICATION                                              0x3800
#define SCSI_ASC_ESN_POWER_MANAGEMENT_CLASS_EVENT                                       0x3802
#define SCSI_ASC_ESN_MEDIA_CLASS_EVENT                                                  0x3804
#define SCSI_ASC_ESN_DEVICE_BUSY_CLASS_EVENT                                            0x3806
#define SCSI_ASC_SAVING_PARAMETERS_NOT_SUPPORTED                                        0x3900
#define SCSI_ASC_MEDIUM_NOT_PRESENT                                                     0x3A00
#define SCSI_ASC_MEDIUM_NOT_PRESENT_TRAY_CLOSED                                         0x3A01
#define SCSI_ASC_MEDIUM_NOT_PRESENT_TRAY_OPEN                                           0x3A02
#define SCSI_ASC_MEDIUM_NOT_PRESENT_LOADABLE                                            0x3A03
#define SCSI_ASC_MEDIUM_NOT_PRESENT_MEDIUM_AUXILIARY_MEMORY_ACCESSIBLE                  0x3A04
#define SCSI_ASC_SEQUENTIAL_POSITIONING_ERROR                                           0x3B00
#define SCSI_ASC_TAPE_POSITION_ERROR_AT_BEGINNINGOF_MEDIUM                              0x3B01
#define SCSI_ASC_TAPE_POSITION_ERROR_AT_ENDOF_MEDIUM                                    0x3B02
#define SCSI_ASC_TAPE_OR_ELECTRONIC_VERTICAL_FORMS_UNIT_NOT_READY                       0x3B03
#define SCSI_ASC_SLEW_FAILURE                                                           0x3B04
#define SCSI_ASC_PAPER_JAM                                                              0x3B05
#define SCSI_ASC_FAILED_TO_SENSE_TOPOF_FORM                                             0x3B06
#define SCSI_ASC_FAILED_TO_SENSE_BOTTOMOF_FORM                                          0x3B07
#define SCSI_ASC_REPOSITION_ERROR                                                       0x3B08
#define SCSI_ASC_READ_PAST_END_OF_MEDIUM                                                0x3B09
#define SCSI_ASC_READ_PAST_BEGINNING_OF_MEDIUM                                          0x3B0A
#define SCSI_ASC_POSITION_PAST_END_OF_MEDIUM                                            0x3B0B
#define SCSI_ASC_POSITION_PAST_BEGINNING_OF_MEDIUM                                      0x3B0C
#define SCSI_ASC_MEDIUM_DESTINATION_ELEMENT_FULL                                        0x3B0D
#define SCSI_ASC_MEDIUM_SOURCE_ELEMENT_EMPTY                                            0x3B0E
#define SCSI_ASC_END_OF_MEDIUM_REACHED                                                  0x3B0F
#define SCSI_ASC_MEDIUM_MAGAZINE_NOT_ACCESSIBLE                                         0x3B11
#define SCSI_ASC_MEDIUM_MAGAZINE_REMOVED                                                0x3B12
#define SCSI_ASC_MEDIUM_MAGAZINE_INSERTED                                               0x3B13
#define SCSI_ASC_MEDIUM_MAGAZINE_LOCKED                                                 0x3B14
#define SCSI_ASC_MEDIUM_MAGAZINE_UNLOCKED                                               0x3B15
#define SCSI_ASC_MECHANICAL_POSITIONING_OR_CHANGER_ERROR                                0x3B16
#define SCSI_ASC_READ_PAST_END_OF_USER_OBJECT                                           0x3B17
#define SCSI_ASC_ELEMENT_DISABLED                                                       0x3B18
#define SCSI_ASC_ELEMENT_ENABLED                                                        0x3B19
#define SCSI_ASC_DATA_TRANSFER_DEVICE_REMOVED                                           0x3B1A
#define SCSI_ASC_DATA_TRANSFER_DEVICE_INSERTED                                          0x3B1B
#define SCSI_ASC_INVALID_BITS_IN_IDENTIFY_MESSAGE                                       0x3D00
#define SCSI_ASC_LOGICAL_UNIT_HAS_NOT_SELFCONFIGURED_YET                                0x3E00
#define SCSI_ASC_LOGICAL_UNIT_FAILURE                                                   0x3E01
#define SCSI_ASC_TIMEOUT_ON_LOGICAL_UNIT                                                0x3E02
#define SCSI_ASC_LOGICAL_UNIT_FAILED_SELFTEST                                           0x3E03
#define SCSI_ASC_LOGICAL_UNIT_UNABLE_TO_UPDATE_SELFTEST_LOG                             0x3E04
#define SCSI_ASC_TARGET_OPERATING_CONDITIONS_HAVE_CHANGED                               0x3F00
#define SCSI_ASC_MICROCODE_HAS_BEEN_CHANGED                                             0x3F01
#define SCSI_ASC_CHANGED_OPERATING_DEFINITION                                           0x3F02
#define SCSI_ASC_INQUIRY_DATA_HAS_CHANGED                                               0x3F03
#define SCSI_ASC_COMPONENT_DEVICE_ATTACHED                                              0x3F04
#define SCSI_ASC_DEVICE_IDENTIFIER_CHANGED                                              0x3F05
#define SCSI_ASC_REDUNDANCY_GROUP_CREATED_OR_MODIFIED                                   0x3F06
#define SCSI_ASC_REDUNDANCY_GROUP_DELETED                                               0x3F07
#define SCSI_ASC_SPARE_CREATED_OR_MODIFIED                                              0x3F08
#define SCSI_ASC_SPARE_DELETED                                                          0x3F09
#define SCSI_ASC_VOLUME_SET_CREATED_OR_MODIFIED                                         0x3F0A
#define SCSI_ASC_VOLUME_SET_DELETED                                                     0x3F0B
#define SCSI_ASC_VOLUME_SET_DEASSIGNED                                                  0x3F0C
#define SCSI_ASC_VOLUME_SET_REASSIGNED                                                  0x3F0D
#define SCSI_ASC_REPORTED_LUNS_DATA_HAS_CHANGED                                         0x3F0E
#define SCSI_ASC_ECHO_BUFFER_OVERWRITTEN                                                0x3F0F
#define SCSI_ASC_MEDIUM_LOADABLE                                                        0x3F10
#define SCSI_ASC_MEDIUM_AUXILIARY_MEMORY_ACCESSIBLE                                     0x3F11
#define SCSI_ASC_LPWR_MAEBK_iSCSI_IP_ADDRESS_ADDED                                      0x3F12
#define SCSI_ASC_LPWR_MAEBK_iSCSI_IP_ADDRESS_REMOVED                                    0x3F13
#define SCSI_ASC_LPWR_MAEBK_iSCSI_IP_ADDRESS_CHANGED                                    0x3F14
#define SCSI_ASC_RAM_FAILURE                                                            0x4000
#define SCSI_ASC_DIAGNOSTIC_FAILURE_ON_COMPONENT_NN                                     0x4000
#define SCSI_ASC_DATA_PATH_FAILURE                                                      0x4100
#define SCSI_ASC_POWERON_OR_SELF_TEST_FAILURE                                           0x4200
#define SCSI_ASC_MESSAGE_ERROR                                                          0x4300
#define SCSI_ASC_INTERNAL_TARGET_FAILURE                                                0x4400
#define SCSI_ASC_ATA_DEVICE_FAILED_SET_FEATURES                                         0x4471
#define SCSI_ASC_SELECT_OR_RESELECT_FAILURE                                             0x4500
#define SCSI_ASC_UNSUCCESSFUL_SOFT_RESET                                                0x4600
#define SCSI_ASC_SCSI_PARITY_ERROR                                                      0x4700
#define SCSI_ASC_DATA_PHASE_CRC_ERROR_DETECTED                                          0x4701
#define SCSI_ASC_SCSI_PARITY_ERROR_DETECTED_DURING_ST_DATA_PHASE                        0x4702
#define SCSI_ASC_INFORMATION_UNIT_CRC_ERROR_DETECTED                                    0x4703
#define SCSI_ASC_ASYNCHRONOUS_INFORMATION_PROTECTION_ERROR_DETECTED                     0x4704
#define SCSI_ASC_PROTOCOL_SERVICE_CRC_ERROR                                             0x4705
#define SCSI_ASC_PHY_TEST_FUNCTION_IN_PROGRESS                                          0x4706
#define SCSI_ASC_SOME_COMMANDS_CLEARED_BY_ISCSI_PROTOCOL_EVENT                          0x477F
#define SCSI_ASC_INITIATOR_DETECTED_ERROR_MESSAGE_RECEIVED                              0x4800
#define SCSI_ASC_INVALID_MESSAGE_ERROR                                                  0x4900
#define SCSI_ASC_COMMAND_PHASE_ERROR                                                    0x4A00
#define SCSI_ASC_DATA_PHASE_ERROR                                                       0x4B00
#define SCSI_ASC_INVALID_TARGET_PORT_TRANSFER_TAG_RECEIVED                              0x4B01
#define SCSI_ASC_TOO_MUCH_WRITE_DATA                                                    0x4B02
#define SCSI_ASC_ACK_NAK_TIMEOUT                                                        0x4B03
#define SCSI_ASC_NAK_RECEIVED                                                           0x4B04
#define SCSI_ASC_DATA_OFFSET_ERROR                                                      0x4B05
#define SCSI_ASC_INITIATOR_RESPONSE_TIMEOUT                                             0x4B06
#define SCSI_ASC_LOGICAL_UNIT_FAILED_SELFCONFIGURATION                                  0x4C00
#define SCSI_ASC_TAGGED_OVERLAPPED_COMMANDS                                             0x4D00
#define SCSI_ASC_OVERLAPPED_COMMANDS_ATTEMPTED                                          0x4E00
#define SCSI_ASC_WRITE_APPEND_ERROR                                                     0x5000
#define SCSI_ASC_WRITE_APPEND_POSITION_ERROR                                            0x5001
#define SCSI_ASC_POSITION_ERROR_RELATED_TO_TIMING                                       0x5002
#define SCSI_ASC_ERASE_FAILURE                                                          0x5100
#define SCSI_ASC_ERASE_FAILURE_INCOMPLETE_ERASE_OPERATION_DETECTED                      0x5101
#define SCSI_ASC_CARTRIDGE_FAULT                                                        0x5200
#define SCSI_ASC_MEDIA_LOAD_OR_EJECT_FAILED                                             0x5300
#define SCSI_ASC_UNLOAD_TAPE_FAILURE                                                    0x5301
#define SCSI_ASC_MEDIUM_REMOVAL_PREVENTED                                               0x5302
#define SCSI_ASC_MEDIUM_REMOVAL_PREVENTED_BY_DATA_TRANSFER_ELEMENT                      0x5303
#define SCSI_ASC_MEDIUM_THREAD_OR_UNTHREAD_FAILURE                                      0x5304
#define SCSI_ASC_SCSI_TO_HOST_SYSTEM_INTERFACE_FAILURE                                  0x5400
#define SCSI_ASC_SYSTEM_RESOURCE_FAILURE                                                0x5500
#define SCSI_ASC_SYSTEM_BUFFER_FULL                                                     0x5501
#define SCSI_ASC_INSUFFICIENT_RESERVATION_RESOURCES                                     0x5502
#define SCSI_ASC_INSUFFICIENT_RESOURCES                                                 0x5503
#define SCSI_ASC_INSUFFICIENT_REGISTRATION_RESOURCES                                    0x5504
#define SCSI_ASC_ACCESS_CONTROL_RESOURCES                                               0x5505
#define SCSI_ASC_AUXILIARY_MEMORY_OUT_OF_SPACE                                          0x5506
#define SCSI_ASC_QUOTA_ERROR                                                            0x5507
#define SCSI_ASC_MAXIMUM_NUMBER_OF_SUPPLEMENTAL_DECRYPTION_KEYS_EXCEEDED                0x5508
#define SCSI_ASC_MEDIUM_AUXILIARY_MEMORY_NOT_ACCESSIBLE                                 0x5509
#define SCSI_ASC_DATA_CURRENTLY_UNAVAILABLE                                             0x550A
#define SCSI_ASC_UNABLE_TO_RECOVER_TABLEOF_CONTENTS                                     0x5700
#define SCSI_ASC_GENERATION_DOES_NOT_EXIST                                              0x5800
#define SCSI_ASC_UPDATED_BLOCK_READ                                                     0x5900
#define SCSI_ASC_LPWRO_OPERATOR_REQUEST_OR_STATE_CHANGE_INPUT                           0x5A00
#define SCSI_ASC_OPERATOR_MEDIUM_REMOVAL_REQUEST                                        0x5A01
#define SCSI_ASC_OPERATOR_SELECTED_WRITE_PROTECT                                        0x5A02
#define SCSI_ASC_OPERATOR_SELECTED_WRITE_PERMIT                                         0x5A03
#define SCSI_ASC_LOG_EXCEPTION                                                          0x5B00
#define SCSI_ASC_THRESHOLD_CONDITION_MET                                                0x5B01
#define SCSI_ASC_LOG_COUNTER_AT_MAXIMUM                                                 0x5B02
#define SCSI_ASC_LOG_LIST_CODES_EXHAUSTED                                               0x5B03
#define SCSI_ASC_RPL_STATUS_CHANGE                                                      0x5C00
#define SCSI_ASC_SPINDLES_SYNCHRONIZED                                                  0x5C01
#define SCSI_ASC_SPINDLES_NOT_SYNCHRONIZED                                              0x5C02
#define SCSI_ASC_FAILURE_PREDICTION_THRESHOLD_EXCEEDED                                  0x5D00
#define SCSI_ASC_MEDIA_FAILURE_PREDICTION_THRESHOLD_EXCEEDED                            0x5D01
#define SCSI_ASC_LOGICAL_UNIT_FAILURE_PREDICTION_THRESHOLD_EXCEEDED                     0x5D02
#define SCSI_ASC_SPARE_AREA_EXHAUSTION_PREDICTION_THRESHOLD_EXCEEDED                    0x5D03
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE                  0x5D10
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH                   0x5D11
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH                    0x5D12
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH                    0x5D13
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS                    0x5D14
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                       0x5D15
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH                   0x5D16
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                         0x5D17
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_CONTROLLER_DETECTED                         0x5D18
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                      0x5D19
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                       0x5D1A
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_SPINUP_RETRY_COUNT                          0x5D1B
#define SCSI_ASC_HARDWARE_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT               0x5D1C
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE                0x5D20
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH                 0x5D21
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH                  0x5D22
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH                  0x5D23
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS                  0x5D24
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                     0x5D25
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH                 0x5D26
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                       0x5D27
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_CONTROLLER_DETECTED                       0x5D28
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                    0x5D29
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                     0x5D2A
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_SPINUP_RETRY_COUNT                        0x5D2B
#define SCSI_ASC_CONTROLLER_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT             0x5D2C
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE              0x5D30
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH               0x5D31
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH                0x5D32
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH                0x5D33
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS                0x5D34
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                   0x5D35
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH               0x5D36
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                     0x5D37
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_CONTROLLER_DETECTED                     0x5D38
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                  0x5D39
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                   0x5D3A
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_SPINUP_RETRY_COUNT                      0x5D3B
#define SCSI_ASC_DATA_CHANNEL_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT           0x5D3C
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE                     0x5D40
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH                      0x5D41
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH                       0x5D42
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH                       0x5D43
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS                       0x5D44
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                          0x5D45
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH                      0x5D46
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                            0x5D47
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_CONTROLLER_DETECTED                            0x5D48
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                         0x5D49
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                          0x5D4A
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_SPINUP_RETRY_COUNT                             0x5D4B
#define SCSI_ASC_SERVO_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT                  0x5D4C
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE                   0x5D50
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH                    0x5D51
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH                     0x5D52
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH                     0x5D53
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS                     0x5D54
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                        0x5D55
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH                    0x5D56
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                          0x5D57
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_CONTROLLER_DETECTED                          0x5D58
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                       0x5D59
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                        0x5D5A
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_SPINUP_RETRY_COUNT                           0x5D5B
#define SCSI_ASC_SPINDLE_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT                0x5D5C
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_GENERAL_HARD_DRIVE_FAILURE                  0x5D60
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_DRIVE_ERROR_RATE_TOO_HIGH                   0x5D61
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_DATA_ERROR_RATE_TOO_HIGH                    0x5D62
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_SEEK_ERROR_RATE_TOO_HIGH                    0x5D63
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_TOO_MANY_BLOCK_REASSIGNS                    0x5D64
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_ACCESS_TIMES_TOO_HIGH                       0x5D65
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_START_UNIT_TIMES_TOO_HIGH                   0x5D66
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_CHANNEL_PARAMETRICS                         0x5D67
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_CONTROLLER_DETECTED                         0x5D68
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_THROUGHPUT_PERFORMANCE                      0x5D69
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_SEEK_TIME_PERFORMANCE                       0x5D6A
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_SPINUP_RETRY_COUNT                          0x5D6B
#define SCSI_ASC_FIRMWARE_IMPENDING_FAILURE_DRIVE_CALIBRATION_RETRY_COUNT               0x5D6C
#define SCSI_ASC_FAILURE_PREDICTION_THRESHOLD_EXCEEDED_FALSE                            0x5DFF
#define SCSI_ASC_LPWROLOW_POWER_CONDITION_ON                                            0x5E00
#define SCSI_ASC_LPWROIDLE_CONDITION_ACTIVATED_BY_TIMER                                 0x5E01
#define SCSI_ASC_LPWROSTANDBY_CONDITION_ACTIVATED_BY_TIMER                              0x5E02
#define SCSI_ASC_LPWROIDLE_CONDITION_ACTIVATED_BY_COMMAND                               0x5E03
#define SCSI_ASC_LPWROSTANDBY_CONDITION_ACTIVATED_BY_COMMAND                            0x5E04
#define SCSI_ASC_POWER_STATE_CHANGE_TO_ACTIVE                                           0x5E41
#define SCSI_ASC_POWER_STATE_CHANGE_TO_IDLE                                             0x5E42
#define SCSI_ASC_POWER_STATE_CHANGE_TO_STANDBY                                          0x5E43
#define SCSI_ASC_POWER_STATE_CHANGE_TO_SLEEP                                            0x5E45
#define SCSI_ASC_POWER_STATE_CHANGE_TO_DEVICE_CONTROL                                   0x5E47
#define SCSI_ASC_LAMP_FAILURE                                                           0x6000
#define SCSI_ASC_VIDEO_ACQUISITION_ERROR                                                0x6100
#define SCSI_ASC_UNABLE_TO_ACQUIRE_VIDEO                                                0x6101
#define SCSI_ASC_OUT_OF_FOCUS                                                           0x6102
#define SCSI_ASC_SCAN_HEAD_POSITIONING_ERROR                                            0x6200
#define SCSI_ASC_END_OF_USER_AREA_ENCOUNTERED_ON_THIS_TRACK                             0x6300
#define SCSI_ASC_PACKET_DOES_NOT_FIT_IN_AVAILABLE_SPACE                                 0x6301
#define SCSI_ASC_ILLEGAL_MODE_FOR_THIS_TRACK                                            0x6400
#define SCSI_ASC_INVALID_PACKET_SIZE                                                    0x6401
#define SCSI_ASC_VOLTAGE_FAULT                                                          0x6500
#define SCSI_ASC_AUTOMATIC_DOCUMENT_FEEDER_COVER_UP                                     0x6600
#define SCSI_ASC_AUTOMATIC_DOCUMENT_FEEDER_LIFT_UP                                      0x6601
#define SCSI_ASC_DOCUMENT_JAM_IN_AUTOMATIC_DOCUMENT_FEEDER                              0x6602
#define SCSI_ASC_DOCUMENT_MISS_FEED_AUTOMATIC_IN_DOCUMENT_FEEDER                        0x6603
#define SCSI_ASC_CONFIGURATION_FAILURE                                                  0x6700
#define SCSI_ASC_CONFIGURATION_OF_INCAPABLE_LOGICAL_UNITS_FAILED                        0x6701
#define SCSI_ASC_ADD_LOGICAL_UNIT_FAILED                                                0x6702
#define SCSI_ASC_MODIFICATION_OF_LOGICAL_UNIT_FAILED                                    0x6703
#define SCSI_ASC_EXCHANGE_OF_LOGICAL_UNIT_FAILED                                        0x6704
#define SCSI_ASC_REMOVE_OF_LOGICAL_UNIT_FAILED                                          0x6705
#define SCSI_ASC_ATTACHMENT_OF_LOGICAL_UNIT_FAILED                                      0x6706
#define SCSI_ASC_CREATION_OF_LOGICAL_UNIT_FAILED                                        0x6707
#define SCSI_ASC_ASSIGN_FAILURE_OCCURRED                                                0x6708
#define SCSI_ASC_MULTIPLY_ASSIGNED_LOGICAL_UNIT                                         0x6709
#define SCSI_ASC_SET_TARGET_PORT_GROUPS_COMMAND_FAILED                                  0x670A
#define SCSI_ASC_ATA_DEVICE_FEATURE_NOT_ENABLED                                         0x670B
#define SCSI_ASC_LOGICAL_UNIT_NOT_CONFIGURED                                            0x6800
#define SCSI_ASC_DATA_LOSS_ON_LOGICAL_UNIT                                              0x6900
#define SCSI_ASC_MULTIPLE_LOGICAL_UNIT_FAILURES                                         0x6901
#define SCSI_ASC_PARITY_DATA_MISMATCH                                                   0x6902
#define SCSI_ASC_INFORMATIONAL_REFER_TO_LOG                                             0x6A00
#define SCSI_ASC_STATE_CHANGE_HAS_OCCURRED                                              0x6B00
#define SCSI_ASC_REDUNDANCY_LEVEL_GOT_BETTER                                            0x6B01
#define SCSI_ASC_REDUNDANCY_LEVEL_GOT_WORSE                                             0x6B02
#define SCSI_ASC_REBUILD_FAILURE_OCCURRED                                               0x6C00
#define SCSI_ASC_RECALCULATE_FAILURE_OCCURRED                                           0x6D00
#define SCSI_ASC_COMMAND_TO_LOGICAL_UNIT_FAILED                                         0x6E00
#define SCSI_ASC_COPY_PROTECTION_KEY_EXCHANGE_FAILURE_AUTHENTICATION_FAILURE            0x6F00
#define SCSI_ASC_COPY_PROTECTION_KEY_EXCHANGE_FAILURE_KEY_NOT_PRESENT                   0x6F01
#define SCSI_ASC_COPY_PROTECTION_KEY_EXCHANGE_FAILURE_KEY_NOT_ESTABLISHED               0x6F02
#define SCSI_ASC_READ_OF_SCRAMBLED_SECTOR_WITHOUT_AUTHENTICATION                        0x6F03
#define SCSI_ASC_MEDIA_REGION_CODE_IS_MISMATCHED_TO_LOGICAL_UNIT_REGION                 0x6F04
#define SCSI_ASC_DRIVE_REGION_MUST_BE_PERMANENT_REGION_RESET_COUNT_ERROR                0x6F05
#define SCSI_ASC_INSUFFICIENT_BLOCK_COUNT_FOR_BINDING_NONCE_RECORDING                   0x6F06
#define SCSI_ASC_CONFLICT_IN_BINDING_NONCE_RECORDING                                    0x6F07
#define SCSI_ASC_DECOMPRESSION_EXCEPTION_SHORT_ALGORITHM_ID_OF_NN                       0x7000
#define SCSI_ASC_DECOMPRESSION_EXCEPTION_LONG_ALGORITHM_ID                              0x7100
#define SCSI_ASC_SESSION_FIXATION_ERROR                                                 0x7200
#define SCSI_ASC_SESSION_FIXATION_ERROR_WRITING_LEADIN                                  0x7201
#define SCSI_ASC_SESSION_FIXATION_ERROR_WRITING_LEADOUT                                 0x7202
#define SCSI_ASC_SESSION_FIXATION_ERROR_INCOMPLETE_TRACK_IN_SESSION                     0x7203
#define SCSI_ASC_EMPTY_OR_PARTIALLY_WRITTEN_RESERVED_TRACK                              0x7204
#define SCSI_ASC_NO_MORE_TRACK_RESERVATIONS_ALLOWED                                     0x7205
#define SCSI_ASC_RMZ_EXTENSION_IS_NOT_ALLOWED                                           0x7206
#define SCSI_ASC_NO_MORE_TEST_ZONE_EXTENSIONS_ARE_ALLOWED                               0x7207
#define SCSI_ASC_CD_CONTROL_ERROR                                                       0x7300
#define SCSI_ASC_POWER_CALIBRATION_AREA_ALMOST_FULL                                     0x7301
#define SCSI_ASC_POWER_CALIBRATION_AREA_IS_FULL                                         0x7302
#define SCSI_ASC_POWER_CALIBRATION_AREA_ERROR                                           0x7303
#define SCSI_ASC_PROGRAM_MEMORY_AREA_UPDATE_FAILURE                                     0x7304
#define SCSI_ASC_PROGRAM_MEMORY_AREA_IS_FULL                                            0x7305
#define SCSI_ASC_RMA_PMA_IS_ALMOST_FULL                                                 0x7306
#define SCSI_ASC_CURRENT_POWER_CALIBRATION_AREA_ALMOST_FULL                             0x7310
#define SCSI_ASC_CURRENT_POWER_CALIBRATION_AREA_IS_FULL                                 0x7311
#define SCSI_ASC_RDZ_IS_FULL                                                            0x7317
#define SCSI_ASC_SECURITY_ERROR                                                         0x7400
#define SCSI_ASC_UNABLE_TO_DECRYPT_DATA                                                 0x7401
#define SCSI_ASC_UNENCRYPTED_DATA_ENCOUNTERED_WHILE_DECRYPTING                          0x7402
#define SCSI_ASC_INCORRECT_DATA_ENCRYPTION_KEY                                          0x7403
#define SCSI_ASC_CRYPTOGRAPHIC_INTEGRITY_VALIDATION_FAILED                              0x7404
#define SCSI_ASC_ERROR_DECRYPTING_DATA                                                  0x7405
#define SCSI_ASC_UNKNOWN_SIGNATURE_VERIFICATION_KEY                                     0x7406
#define SCSI_ASC_ENCRYPTION_PARAMETERS_NOT_USEABLE                                      0x7407
#define SCSI_ASC_E_VF_DIGITAL_SIGNATURE_VALIDATION_FAILURE                              0x7408
#define SCSI_ASC_ENCRYPTION_MODE_MISMATCH_ON_READ                                       0x7409
#define SCSI_ASC_ENCRYPTED_BLOCK_NOT_RAW_READ_ENABLED                                   0x740A
#define SCSI_ASC_INCORRECT_ENCRYPTION_PARAMETERS                                        0x740B
#define SCSI_ASC_UNABLE_TO_DECRYPT_PARAMETER_LIST                                       0x740C
#define SCSI_ASC_ENCRYPTION_ALGORITHM_DISABLED                                          0x740D
#define SCSI_ASC_CREATION_PARAMETER_VALUE_INVALID                                       0x7410
#define SCSI_ASC_CREATION_PARAMETER_VALUE_REJECTED                                      0x7411
#define SCSI_ASC_INVALID_SA_USAGE                                                       0x7412
#define SCSI_ASC_DATA_ENCRYPTION_CONFIGURATION_PREVENTED                                0x7421
#define SCSI_ASC_CREATION_PARAMETER_NOT_SUPPORTED                                       0x7430
#define SCSI_ASC_AUTHENTICATION_FAILED                                                  0x7440
#define SCSI_ASC_EXTERNAL_DATA_ENCRYPTION_KEY_MANAGER_ACCESS_ERROR                      0x7461
#define SCSI_ASC_EXTERNAL_DATA_ENCRYPTION_KEY_MANAGER_ERROR                             0x7462
#define SCSI_ASC_EXTERNAL_DATA_ENCRYPTION_KEY_NOT_FOUND                                 0x7463
#define SCSI_ASC_EXTERNAL_DATA_ENCRYPTION_REQUEST_NOT_AUTHORIZED                        0x7464
#define SCSI_ASC_EXTERNAL_DATA_ENCRYPTION_CONTROL_TIMEOUT                               0x746E
#define SCSI_ASC_EXTERNAL_DATA_ENCRYPTION_CONTROL_ERROR                                 0x746F
#define SCSI_ASC_LOGICAL_UNIT_ACCESS_NOT_AUTHORIZED                                     0x7471
#define SCSI_ASC_SECURITY_CONFLICT_IN_TRANSLATED_DEVICE                                 0x7479
#define SCSI_ASC_FWIIO_CMD_ERROR                                                        0x88FD
#define SCSI_ASC_SR1216_SPECIFIC_DATA_OBJECT_DOWNLOAD_ERROR                             0x88FE

#endif // __SCSI_ASC_ASCQ_H__
